### PR TITLE
Fixes for Python 3

### PR DESCRIPTION
**Pull request by xangma**
- xrange is no longer used in Python 3.
- print statements need parentheses in Python 3.
- F needs to be converted into a list …

I think this is all I had to change to get it working in Python 3.

### CODE REVIEW

**Comment by xangma** [comment]
These edits seem to work with Python 2 too.

**Comment by xangma** [comment]
It seems comparison has changed between Python 2 and 3. See here: http://stackoverflow.com/questions/7969552/why-does-4-3-return-true-in-python-2

Had to change the while statement to accommodate. The reason I didn't pick that up is because I had set n_features to an integer myself when using the function, but example.py keeps n_features at the default value of 'auto'.

@shahlaebrahimi Yeah, I probably should have done that. I was in a bit of a rush and just needed it to work =P

**Comment by davidrpugh** [comment]
@xangma or @danielhomola Are there any unit or functional tests that you are running to check that mifs works as expected?  I would be happy to submit a PR for integration with Travis CI, that would allow tests to be run against Python 2 and 3 to prevent such issues from arising in the future.

**Comment by shahlaebrahimi** [comment]
@xangma I have been told that: "Python 2 has this weird behavior that a string is always “greater” than an int. E.g., 

 `'123' > 1
`
True
`'1' > 123`
True

Thus it’s actually a good thing that Python 3 throws an error at that so someone can look into it and fix it. 

What I mean by “what ‘auto’ is supposed to do” is that it depends on how you fould specify/asses how many features you’d want to select. E.g., you can have an additional if-else check in there.

You probably want to do something like

` while (self.n_features==‘auto’ and some_other_criterion) or len(S) < self.n_features:`"
Thanks.

**Comment by danielhomola** [comment]
Hi,

thanks for the work. I can accept these changes given a few changes:
- please make sure your code respects PEP, and you write F = list(F) instead of F=list(F), and do the same in the while statement with "auto". 
- could you explain is F = list(F) necessary?
- putting print() will break python2, so please import print_function from future to ensure python 2 is covered as well.

**Comment by shahlaebrahimi** [comment]
According to [this line ](https://github.com/danielhomola/mifs/blob/master/mifs.py#L70) in conjunction with [this one](https://github.com/danielhomola/mifs/blob/master/mifs.py#L245), it seems that an additional condition in while loop is needed while doing automatic selection. However, it may be related to [this](https://github.com/danielhomola/mifs/blob/master/mifs.py#L261). Really, I do not know why `len(S) > 10` when it automatically selects?

Thanks in advance.

**Comment by shahlaebrahimi** [comment]
This [article](http://www.tandfonline.com/doi/abs/10.1080/18756891.2016.1204120?journalCode=tcis20) as well as this [one ](http://www.sciencedirect.com/science/article/pii/S0925231209002008) may be useful for stopping criterion. 
Thanks.

**Comment by shahlaebrahimi** [comment]
Based on [this](http://stackoverflow.com/questions/15014310/why-is-there-no-xrange-function-in-python3): "Wherever you were using xrange in python 2, use range in python 3. It does what xrange used to do, which is return an iterator. If you need the results in a list, do list(range(..)). That is equivalent to python 2's range. Or to say it another way: xrange has been renamed range, because it is the better default; it wasn't necessary to have both, do list(range) if you really need a list."

**Comment by davidrpugh** [comment]
@danielhomola I don't think `F=list(F)` is necessary.  In python 3 `F=range(10)` returns in iterator object instead of a plain list, but since both lists and iterators can be indexed I don't think it matters.

**Comment by shahlaebrahimi** [comment]
@davidrpugh Thanks. However, it throws an error when I do not use list():

```
Traceback (most recent call last):
  File "D:/mifs-master_2/mifs-master/untitled0.py", line 21, in <module>
    feat_selector.fit(X, y)
  File "D:\mifs-master_2\mifs-master\mifs.py", line 137, in fit
    return self._fit(X, y)
  File "D:\mifs-master_2\mifs-master\mifs.py", line 211, in _fit
    S, F = self._add_remove(S, F, bn.nanargmax(xy_MI))
  File "D:\mifs-master_2\mifs-master\mifs.py", line 316, in _add_remove
    F.remove(i)
AttributeError: 'range' object has no attribute 'remove'

Process finished with exit code 1
```

**Comment by davidrpugh** [comment]
@shahlaebrahimi Indeed. I saw indexing but missed the call to the remove method which only exists on a list object.  However, rather than forcing `F` to be a list inside the `_add_remove` function, I think a better fix would be to make sure that the original `F` is a list when it is initialized [here](https://github.com/danielhomola/mifs/pull/4/commits/7ca1dc3ded853e91b4e4e5705d7b587f9c61856b#diff-039fc1f021d83fa8cf90a78bed4082beR188).  I would change line 188 from
    
    F = range(p)

to

    F = list(range(p))

and leave the `_add_remove` function alone.

**Comment by shahlaebrahimi** [comment]
Maybe we need to figure out n_features in the [_fit method ](https://github.com/danielhomola/mifs/blob/master/mifs.py#L180) before this loop in case in [self.n_features == 'auto'](https://github.com/danielhomola/mifs/blob/master/mifs.py#L194). It seems that  it influences important condition in the while loop, which results in "ValueError: All-NaN slice encountered" in case of small or large data sets. How n-feature is calculated?

**Comment by shahlaebrahimi** [comment]
Could you please run the original code (in Python 2) using a small data set E.g., 14 features?

**Comment by shahlaebrahimi** [comment]
This [script ](https://github.com/chiewoo/GRBCode/blob/45f174d9bdc9c821fc23feeaf0c9dfe84a629ae0/compute_mic.py#L125) seemingly implements automatic feature selection based on normalized mutual information, so it may provide an insight about the problem with automatic selection.
However, the author is in the best place to figure it out.

**Comment by danielhomola** [comment]
Accepted latest pull request that addresses these issues.

**Pull request closed without merging**
