### PR TITLE
[WIP] Package refactoring

### PR DESCRIPTION
**Pull request by glemaitre**
For my purpose, I needed the package to be installed.

I made a couple of changes. If you can let me know if it is interesting you, I could push to finalize the PR.

### CODE REVIEW

**Comment by shahlaebrahimi** [comment]
@glemaitre Sorry, it seems that there is some problem with this code. Could you resolve it? 
Thanks

**Comment by glemaitre** [comment]
@shahlaebrahimi can you be more specific?

**Comment by shahlaebrahimi** [comment]
@glemaitre Could you please look at the issues related to this code? Seemingly, there is some problem with automatic selection, especially when MRMR is tested on large or small data sets.

**Comment by glemaitre** [comment]
Ok but this is not related with my PR, isn't?

**Comment by danielhomola** [comment]
Hi,

Really sorry for my long absence. Thanks a lot for this PR. Could you please explain what's the benefit of the makefile? Also could you please revert the readme file to it's previous version? Then I can accept this PR. Many thanks!

**Comment by glemaitre** [comment]
@danielhomola The benefit of the make file is to automatize the test, the doc, and clean the folder with `pyc`. I will change the README. I don't remember exactly why it is interesting to have an `rst` instead of an `md`. If I recall well, on pypi `rst` is interpreted and not `md`.

**Comment by glemaitre** [comment]
Normally, I removed the doc from the README since that you can automatically create it with `sphinx` now. I will add it again and you can see if you want to remove it afterwards.

**Comment by glemaitre** [comment]
@danielhomola Look good on my side

**Comment by danielhomola** [comment]
thanks a lot for this work! we'd need to write tests as well for this package to be truly robust.. will try and do that in the coming months..

**Pull request merged**
